trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - src/TourManager
    

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    pool:
      vmImage: ubuntu-latest
    displayName: Build and push the image
    jobs:
    - job: build_image
      displayName: Build image
      steps:
      - task: Docker@2
        inputs:
          command: buildAndPush
          containerRegistry: registry.travely.am
          repository: travely/tourmanager-api
          Dockerfile: $(Build.SourcesDirectory)/src/TourManager/TourManager.Api/Dockerfile
          buildContext: $(Build.SourcesDirectory)
          tags: |
            latest
            $(Build.BuildId)
  - stage: Deploy
    pool:
      vmImage: ubuntu-latest
    jobs:
    - deployment: Deploy
      displayName: Deploy app
      environment: dev.dev-travely-am
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                # namespace: dev-travely-am
                #kubernetesServiceConnection: 'dev-dev-travely-am-1637185039689'
                manifests: 'devops/tourmanager-api/k8s/*.yaml'
                #imagePullSecrets: 'regcred'