apiVersion: v1
kind: Service
metadata:
  name: propertymanager-api
  namespace: travely-dev
spec:
  selector:
    app: propertymanager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80