apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: travely-dev
spec:
  selector:
    matchLabels:
      app: identity-api
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: api
        image: localhost:32000/travely/identity-api
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mssql;Database=Identity;User=sa;Password=I7yxNP8STsnd+H3yfWvAIg==;
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        ports:
        - containerPort: 80